"use client";
import {useState} from "react";
import Shell from "./Shell";
import {Bot,Send,Sparkles,User} from "lucide-react";
import {strategies} from "@/data/strategies";
const suggestions=["Criar estratégia de humanização","Resumir notícias do Radar","Montar calendário editorial","Comparar posicionamento dos candidatos"];
function answer(q:string){const t=q.toLowerCase();const s=t.includes("humor")?strategies[4]:t.includes("crítica")||t.includes("responder")?strategies[5]:t.includes("podcast")?strategies[3]:t.includes("human")?strategies[2]:strategies[0];return `DIAGNÓSTICO\n${s.objective}\n\nEVIDÊNCIA DISPONÍVEL\n${s.rationale}\n\nRECOMENDAÇÕES\n• ${s.actions.slice(0,3).join("\n• ")}\n\nLIMITAÇÕES\nResposta demonstrativa baseada na síntese local dos estudos. Não utiliza dados reais dos perfis nem garante resultado.`}
export default function AiDemo(){
 const[messages,setMessages]=useState<{role:"user"|"bot",text:string}[]>([]),[input,setInput]=useState("");
 function send(text=input){if(!text.trim())return;setMessages(m=>[...m,{role:"user",text},{role:"bot",text:answer(text)}]);setInput("")}
 return <Shell title="Arcanum Assistente"><div className="ai-shell"><section className="ai-welcome"><div className="mx-auto mb-5 w-12 h-12 rounded-2xl grid place-items-center bg-[color-mix(in_srgb,var(--primary)_14%,var(--card))] text-[var(--primary)]"><Sparkles size={22}/></div><span className="eyebrow">ASSISTENTE ESTRATÉGICO</span><h1>Como posso ajudar sua campanha hoje?</h1><p>Organize ideias, transforme dados em pauta e prepare decisões com mais clareza.</p></section><div className="suggestion-row">{suggestions.map(s=><button onClick={()=>send(s)} key={s}>{s}</button>)}</div><div className="chat-stream">{messages.length===0?<div className="h-full min-h-[370px] grid place-items-center text-center muted"><div><Bot className="mx-auto mb-4 opacity-50" size={34}/><p>Escolha uma sugestão ou escreva uma pergunta para começar.</p></div></div>:messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}><div className="chat-avatar">{m.role==="bot"?<Bot size={18}/>:<User size={18}/>}</div><div><span>{m.role==="bot"?"Arcanum":"Você"}</span><p>{m.text}</p></div></div>)}</div><div className="chat-input"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Pergunte sobre estratégia, conteúdo ou reputação..."/><button aria-label="Enviar" onClick={()=>send()}><Send size={18}/></button></div></div></Shell>
}