"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {CalendarDays,Clock3,MapPin,Plus,Search,Trash2,UserRound,X,Loader2} from "lucide-react";
import {CalendarEvent,CalendarEventStatus,CalendarEventType,deleteCalendarEvent,listCalendarEvents,saveCalendarEvent} from "@/lib/calendar-store";

const typeLabels:Record<CalendarEventType,string>={agenda:"Agenda",prazo:"Prazo",conteudo:"Conteúdo",reuniao:"Reunião",evento:"Evento"};
const statusLabels:Record<CalendarEventStatus,string>={planejado:"Planejado",confirmado:"Confirmado",concluido:"Concluído",cancelado:"Cancelado"};
const empty={title:"",description:"",event_type:"agenda" as CalendarEventType,status:"planejado" as CalendarEventStatus,starts_at:"",ends_at:"",location:"",responsible:""};

type EventForm=typeof empty;

export default function CalendarManager(){
 const[events,setEvents]=useState<CalendarEvent[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[error,setError]=useState(""),[editId,setEditId]=useState<string|null>(null),[form,setForm]=useState<EventForm>(empty);
 async function load(){setLoading(true);setError("");try{setEvents(await listCalendarEvents())}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar a agenda.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const handler=()=>void load();window.addEventListener("arcanum:campaign-changed",handler);return()=>window.removeEventListener("arcanum:campaign-changed",handler)},[]);
 const filtered=useMemo(()=>events.filter(e=>`${e.title} ${e.description} ${e.location} ${e.responsible} ${typeLabels[e.event_type]}`.toLowerCase().includes(query.toLowerCase())),[events,query]);
 const upcoming=filtered.filter(e=>new Date(e.starts_at).getTime()>=Date.now()&&e.status!=="cancelado");
 function startNew(){setEditId(null);setForm(empty);setOpen(true)}
 function startEdit(e:CalendarEvent){setEditId(e.id);setForm({title:e.title,description:e.description,event_type:e.event_type,status:e.status,starts_at:e.starts_at.slice(0,16),ends_at:e.ends_at?e.ends_at.slice(0,16):"",location:e.location,responsible:e.responsible});setOpen(true)}
 async function submit(ev:FormEvent){ev.preventDefault();setSaving(true);setError("");try{await saveCalendarEvent({...form,starts_at:new Date(form.starts_at).toISOString(),ends_at:form.ends_at?new Date(form.ends_at).toISOString():null},editId||undefined);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar compromisso.")}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm("Excluir este compromisso?"))return;try{await deleteCalendarEvent(id);setEvents(current=>current.filter(e=>e.id!==id))}catch(e){setError(e instanceof Error?e.message:"Erro ao excluir compromisso.")}}
 return <div className="space-y-6">
  <section className="page-hero flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><span className="eyebrow">OPERAÇÃO DE CAMPANHA</span><h1>Agenda estratégica</h1><p>Compromissos, reuniões, prazos e eventos vinculados à campanha selecionada.</p></div><button className="primary-btn" onClick={startNew}><Plus size={18}/> Novo compromisso</button></section>
  <section className="grid md:grid-cols-3 gap-4"><div className="metric-card"><span className="metric-label">Compromissos</span><strong>{events.length}</strong><small>na campanha atual</small></div><div className="metric-card"><span className="metric-label">Próximos</span><strong>{upcoming.length}</strong><small>pendentes na agenda</small></div><div className="metric-card"><span className="metric-label">Concluídos</span><strong>{events.filter(e=>e.status==="concluido").length}</strong><small>registros finalizados</small></div></section>
  <div className="card p-4 flex items-center gap-3"><Search size={18} className="muted"/><input className="plain-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar compromisso, responsável ou local..."/><span className="badge">{filtered.length} itens</span></div>
  {error&&<div className="error-banner">{error}</div>}
  {loading?<div className="card p-14 grid place-items-center"><Loader2 className="animate-spin"/></div>:<div className="space-y-3">{filtered.map(e=><article key={e.id} className="card p-5 flex flex-col lg:flex-row lg:items-center gap-4"><div className="w-14 h-14 rounded-2xl border border-[var(--border)] grid place-items-center"><CalendarDays size={22}/></div><div className="flex-1 min-w-0"><div className="flex flex-wrap gap-2 mb-2"><span className="badge">{typeLabels[e.event_type]}</span><span className={`status-pill ${e.status==="confirmado"||e.status==="concluido"?"ativa":""}`}>{statusLabels[e.status]}</span></div><h3 className="text-lg font-bold">{e.title}</h3>{e.description&&<p className="muted text-sm mt-1">{e.description}</p>}<div className="profile-meta mt-3"><span><Clock3 size={15}/>{new Date(e.starts_at).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</span>{e.location&&<span><MapPin size={15}/>{e.location}</span>}{e.responsible&&<span><UserRound size={15}/>{e.responsible}</span>}</div></div><div className="flex gap-2"><button className="icon-btn" onClick={()=>startEdit(e)}>Editar</button><button className="icon-btn danger" onClick={()=>void remove(e.id)}><Trash2 size={16}/></button></div></article>)}{!filtered.length&&<div className="card p-12 text-center muted">Nenhum compromisso cadastrado nesta campanha.</div>}</div>}
  {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="modal-card" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between items-start"><div><h2>{editId?"Editar compromisso":"Novo compromisso"}</h2><p>O registro será vinculado à campanha ativa.</p></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X size={18}/></button></div><label>Título *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Descrição<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-grid"><label>Tipo<select value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value as CalendarEventType})}>{Object.entries(typeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as CalendarEventStatus})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="form-grid"><label>Início *<input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Término<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div><div className="form-grid"><label>Local<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Responsável<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></label></div><button disabled={saving} className="primary-btn justify-center">{saving&&<Loader2 size={17} className="animate-spin"/>} Salvar compromisso</button></form></div>}
 </div>
}
