"use client";
import {useState} from "react";
import Shell from "./Shell";
import {Copy,Film,Layers3,MessageSquareText,Sparkles} from "lucide-react";
const plans={
 "Autoridade":{hook:"O que muda na prática?",script:"Abra com uma dúvida real, explique o contexto em uma frase, apresente a ação, mostre uma evidência e conclua com o benefício concreto.",formats:["Reel de 45–60s","Carrossel de 6 páginas","Stories com caixa de perguntas"],check:["Fonte e data visíveis","Linguagem simples","Benefício concreto","Sem promessa absoluta"]},
 "Proximidade":{hook:"Por trás de cada decisão, existem pessoas.",script:"Registre uma situação real, escute antes de falar, conecte a história a uma ação pública e evite transformar o cidadão em cenário.",formats:["Mini-documentário","Bastidores","Depoimento consentido"],check:["Consentimento","Contexto","Dignidade","Coerência com trajetória"]},
 "Serviço":{hook:"Salve este conteúdo: você pode precisar.",script:"Explique quem tem direito, como acessar, documentos necessários, prazo e canal oficial. Termine orientando onde confirmar a informação.",formats:["Carrossel utilitário","Vídeo tutorial","Card para WhatsApp"],check:["Canal oficial","Data de atualização","Passo a passo","Acessibilidade"]}
};
export default function ContentStudio(){const[pillar,setPillar]=useState<keyof typeof plans>("Autoridade"),[copied,setCopied]=useState(false);const p=plans[pillar];async function copy(){await navigator.clipboard.writeText(`${p.hook}\n\n${p.script}\n\n${p.formats.join(" • ")}`);setCopied(true);setTimeout(()=>setCopied(false),1600)}return <Shell title="Estúdio de Conteúdo"><div className="space-y-5"><section className="page-hero"><div><span className="eyebrow">PLANEJAMENTO EDITORIAL</span><h1>Briefings prontos para adaptar</h1><p>Escolha um pilar e transforme a estratégia em formatos claros para produção.</p></div><div className="metric-icon"><Sparkles size={21}/></div></section><div className="studio-layout"><aside className="studio-sidebar"><h3>Pilar principal</h3>{Object.keys(plans).map(k=><button className={pillar===k?"active":""} onClick={()=>setPillar(k as keyof typeof plans)} key={k}>{k}</button>)}<div className="notice-box">Modelos locais e editáveis. Revise fontes, datas e adequação antes de publicar.</div></aside><main className="brief-card"><div className="brief-label">BRIEFING · {pillar.toUpperCase()}</div><h2>{p.hook}</h2><div className="brief-block"><MessageSquareText/><div><b>Estrutura narrativa</b><p>{p.script}</p></div></div><div className="brief-block"><Film/><div><b>Formatos recomendados</b><div className="tag-row">{p.formats.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="brief-block"><Layers3/><div><b>Checklist editorial</b><ul>{p.check.map(x=><li key={x}>{x}</li>)}</ul></div></div><button className="btn" onClick={copy}><Copy size={16}/> {copied?"Briefing copiado":"Copiar briefing"}</button></main></div></div></Shell>}