import Shell from "./Shell";import ElectionCountdown from "./ElectionCountdown";import {Metric,Section,Progress} from "./Widgets";import {TrendChart,StrategyRadar} from "./Charts";import {candidates} from "@/data/content";import Link from "next/link";
import {BarChart3, BrainCircuit, CheckCircle2, Gauge, ArrowUpRight, CalendarClock, Video, Users, FileCheck2, Lightbulb, AlertTriangle, Clock3} from "lucide-react";
const agenda=[{time:"09:00",title:"Reunião de alinhamento",type:"Estratégia",icon:Users},{time:"11:30",title:"Gravação de conteúdo",type:"Produção",icon:Video},{time:"15:00",title:"Revisão do calendário",type:"Planejamento",icon:CalendarClock},{time:"17:00",title:"Fechamento do relatório",type:"Relatórios",icon:FileCheck2}];
export default function Dashboard(){return <Shell title="Visão Geral">
 <ElectionCountdown/>
 <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-5"><Metric icon={<Gauge size={19}/>} title="Marketing Score" value="88/100" note="Desempenho estratégico consolidado"/><Metric icon={<BarChart3 size={19}/>} title="Branding Score" value="91/100" note="Posicionamento consistente" trend="+2,8%"/><Metric icon={<CheckCircle2 size={19}/>} title="Consistência" value="84%" note="Frequência editorial estável" trend="+6,1%"/><Metric icon={<BrainCircuit size={19}/>} title="Insights" value="18" note="Recomendações simuladas" trend="+5 novos"/></div>
 <div className="grid xl:grid-cols-[1.45fr_.75fr] gap-5 mt-5"><Section title="Evolução Estratégica" action={<button className="soft-btn">Últimas 8 semanas</button>}><TrendChart/></Section><Section title="Diagnóstico Geral"><div className="score-overview"><div className="score-ring"><span>88</span><small>/100</small></div><div><b>Saúde estratégica</b><p className="text-xs muted mt-1">Desempenho demonstrativo geral</p></div></div><div className="space-y-4 mt-6"><Progress label="Comunicação" value={88}/><Progress label="Branding" value={91}/><Progress label="Autoridade" value={90}/><Progress label="Humanização" value={82}/><button className="btn w-full mt-2">Gerar diagnóstico visual</button></div></Section></div>
 <div className="grid xl:grid-cols-[1fr_.78fr] gap-5 mt-5"><Section title="Radar de Temas"><StrategyRadar/></Section><Section title="Agenda de hoje" action={<button className="soft-btn">Ver agenda</button>}><div className="space-y-2">{agenda.map(({time,title,type,icon:Icon})=><div className="agenda-row" key={time}><div className="agenda-time">{time}</div><div className="agenda-icon"><Icon size={17}/></div><div className="flex-1"><b className="text-sm">{title}</b><div className="text-xs muted mt-1">{type}</div></div><ArrowUpRight size={16} className="muted"/></div>)}</div></Section></div>
 <div className="grid lg:grid-cols-2 gap-5 mt-5">{Object.entries(candidates).map(([key,c])=><div className="candidate-card" key={key}><div className="candidate-top"><div className="candidate-avatar">{c.initials}</div><div className="flex-1"><h3 className="text-xl font-bold">{c.name}</h3><p className="muted text-sm">{c.instagram}</p></div><span className="status-dot">Ativo</span></div><p className="mt-5 muted leading-relaxed">{c.description}</p><div className="grid grid-cols-2 gap-3 mt-5">{c.labels.map((l,i)=><div className="score-box" key={l}><div className="text-xs muted">{l}</div><div className="flex items-end justify-between mt-1"><b className="text-2xl">{c.scores[i]}</b><span className="text-xs text-emerald-600">+{i+2}%</span></div></div>)}</div><div className="flex flex-wrap gap-2 mt-4">{c.themes.map(t=><span className="badge" key={t}>{t}</span>)}</div><Link className="btn inline-flex items-center gap-2 mt-5" href={key==='ana'?'/candidatos/ana-carolina':'/candidatos/paulo-serra'}>Abrir estratégia <ArrowUpRight size={16}/></Link></div>)}</div>
 <div className="grid xl:grid-cols-2 gap-5 mt-5"><Section title="Recomendações do Arcanum"><div className="insight-list">{["Conectar entregas de gestão a benefícios concretos.","Aumentar a presença de narrativas humanas recorrentes.","Criar uma série editorial semanal de autoridade."].map((x,i)=><div className="insight-row" key={x}><div className="insight-number">0{i+1}</div><div><b>{x}</b><p className="text-xs muted mt-1">Recomendação demonstrativa baseada nos dados locais.</p></div><Lightbulb size={18}/></div>)}</div></Section><Section title="Alertas estratégicos"><div className="space-y-3"><div className="alert-row warning"><AlertTriangle size={18}/><div><b>Tema com baixa frequência</b><p>Inovação apareceu abaixo da média planejada.</p></div><span>Prioridade</span></div><div className="alert-row"><Clock3 size={18}/><div><b>Conteúdo aguardando revisão</b><p>Três entregas estão próximas do prazo.</p></div><span>Hoje</span></div><div className="alert-row"><FileCheck2 size={18}/><div><b>Relatório semanal</b><p>Modelo disponível para preenchimento.</p></div><span>Pendente</span></div></div></Section></div>
 </Shell>}
