"use client";
import Shell from "./Shell";import {Section,Progress} from "./Widgets";import {useState} from "react";import {ArrowUpRight,CheckCircle2,Clock3,Filter,Plus,Search,Star,MoreHorizontal} from "lucide-react";
const items={
"Estratégia":["Objetivos e prioridades","Pilares e narrativas","Matriz esforço x impacto","Plano de 7, 30 e 90 dias","Linha do tempo e responsáveis","Riscos e oportunidades"],
"Marketing":["Posicionamento","Proposta de valor","Pesquisa e planejamento","Funil de comunicação","Conteúdo e reputação","Métricas e crise"],
"Branding":["DNA da marca","Essência e propósito","Personalidade e arquétipos","Tom de voz","Identidade visual","Consistência"],
"Redes Sociais":["Visão multicanal","Distribuição de formatos","Frequência semanal","Temas predominantes","Posts demonstrativos","Exportação visual"],
"Biblioteca":["Marketing político","Branding","Storytelling","Copywriting","Artigos e estudos","Cases educacionais"],
"Clipping":["Monitoramento demonstrativo","Sentimento","Impacto potencial","Notas internas","Filtros e busca","Status de revisão"],
"Planejamento":["Calendário mensal","Calendário semanal","Kanban","Tarefas e responsáveis","Campanhas e eventos","Prazos e prioridades"],
"Relatórios":["Diagnóstico estratégico","Branding","Redes sociais","Comparativo","Plano editorial","Resumo executivo"],
"Configurações":["Nome e subtítulo","Tema visual","Preferências de relatório","Idioma","Exportar dados locais","Limpar dados demonstrativos"]};
const activity=["Plano editorial atualizado","Revisão de posicionamento concluída","Novo conteúdo adicionado à biblioteca","Relatório semanal preparado"];
export default function GenericPage({title}:{title:keyof typeof items}){const [tab,setTab]=useState("Visão geral");return <Shell title={title}>
<div className="page-hero"><div><span className="badge">Módulo visual • Dados locais</span><h2>{title}</h2><p>Central organizada para análise, operação e acompanhamento. Estrutura preparada para receber backend e dados reais.</p></div><div className="flex gap-2 flex-wrap"><button className="soft-btn"><Filter size={15}/> Filtros</button><button className="btn inline-flex items-center gap-2"><Plus size={16}/> Novo registro</button></div></div>
<div className="module-tabs">{["Visão geral","Atividade","Indicadores","Arquivos"].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</div>
<div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-5"><div className="metric-card"><span className="muted text-xs">Itens ativos</span><b className="text-3xl block mt-2">24</b><span className="trend-pill mt-3">+8% no período</span></div><div className="metric-card"><span className="muted text-xs">Concluídos</span><b className="text-3xl block mt-2">18</b><span className="text-xs muted mt-3 block">75% de conclusão</span></div><div className="metric-card"><span className="muted text-xs">Em revisão</span><b className="text-3xl block mt-2">4</b><span className="text-xs muted mt-3 block">2 com prioridade alta</span></div><div className="metric-card"><span className="muted text-xs">Saúde do módulo</span><b className="text-3xl block mt-2">89%</b><Progress label="" value={89}/></div></div>
<div className="grid xl:grid-cols-[1.5fr_.72fr] gap-5 mt-5"><Section title={`${tab} de ${title}`} action={<div className="mini-search"><Search size={15}/><span>Buscar</span></div>}><div className="module-grid">{items[title].map((x,i)=><article className="module-card" key={x}><div className="module-card-top"><div className="module-icon">{String(i+1).padStart(2,'0')}</div><button className="icon-btn"><MoreHorizontal size={17}/></button></div><h3>{x}</h3><p>Conteúdo demonstrativo estruturado, com visão executiva, status e ações rápidas.</p><div className="module-meta"><span><CheckCircle2 size={14}/> {i%2===0?'Concluído':'Em andamento'}</span><span><Clock3 size={14}/> {i+2} dias</span></div><button className="module-link">Abrir módulo <ArrowUpRight size={15}/></button></article>)}</div></Section><div className="space-y-5"><Section title="Atividade recente">{activity.map((x,i)=><div className="activity-row" key={x}><div className="activity-dot"/><div><b>{x}</b><p>{i+1}h atrás • Marketing 2026</p></div></div>)}</Section><Section title="Favoritos"><div className="space-y-2">{items[title].slice(0,3).map(x=><button className="favorite-row" key={x}><Star size={16}/><span>{x}</span><ArrowUpRight size={14}/></button>)}</div></Section></div></div>
</Shell>}
