"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Download,FileText,Loader2,Plus,Search,Trash2,UploadCloud,X} from "lucide-react";
import {deleteDocument,downloadDocument,LibraryDocument,listDocuments,uploadDocument} from "@/lib/library-store";

const categories=["Estratégia","Jurídico","Pesquisa","Comunicação","Imprensa","Conteúdo","Financeiro","Outros"];
const size=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;

export default function LibraryManager(){
 const[docs,setDocs]=useState<LibraryDocument[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("Todos"),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setDocs(await listDocuments())}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar documentos.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const h=()=>void load();window.addEventListener("arcanum:campaign-changed",h);return()=>window.removeEventListener("arcanum:campaign-changed",h)},[]);
 const filtered=useMemo(()=>docs.filter(d=>(category==="Todos"||d.category===category)&&`${d.name} ${d.description} ${d.category} ${d.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[docs,query,category]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);const file=f.get("file");try{if(!(file instanceof File)||!file.size)throw new Error("Selecione um arquivo.");if(file.size>20*1024*1024)throw new Error("O arquivo deve ter no máximo 20 MB.");await uploadDocument(file,{description:String(f.get("description")||""),category:String(f.get("category")||"Outros"),tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean)});setOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:"Erro ao enviar arquivo.")}finally{setSaving(false)}}
 async function remove(doc:LibraryDocument){if(!confirm(`Excluir ${doc.name}?`))return;try{await deleteDocument(doc);setDocs(x=>x.filter(d=>d.id!==doc.id))}catch(e){setError(e instanceof Error?e.message:"Erro ao excluir documento.")}}
 return <div className="space-y-6">
  <section className="page-hero flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><span className="eyebrow">BASE DE CONHECIMENTO</span><h1>Biblioteca inteligente</h1><p>Centralize arquivos e referências da campanha selecionada.</p></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={18}/> Adicionar documento</button></section>
  <section className="grid md:grid-cols-3 gap-4"><div className="metric-card"><span className="metric-label">Documentos</span><strong>{docs.length}</strong><small>na campanha atual</small></div><div className="metric-card"><span className="metric-label">Categorias</span><strong>{new Set(docs.map(d=>d.category)).size}</strong><small>áreas organizadas</small></div><div className="metric-card"><span className="metric-label">Armazenamento</span><strong>{size(docs.reduce((a,d)=>a+d.file_size,0))}</strong><small>arquivos cadastrados</small></div></section>
  <div className="card p-4 flex flex-col md:flex-row gap-3"><div className="flex items-center gap-3 flex-1"><Search size={18} className="muted"/><input className="plain-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, descrição, categoria ou tag..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>Todos</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div>
  {error&&<div className="error-banner">{error}</div>}
  {loading?<div className="card p-14 grid place-items-center"><Loader2 className="animate-spin"/></div>:<div className="grid lg:grid-cols-2 gap-4">{filtered.map(doc=><article className="card p-5" key={doc.id}><div className="flex gap-4"><div className="w-12 h-12 rounded-xl border border-[var(--border)] grid place-items-center"><FileText size={22}/></div><div className="flex-1 min-w-0"><div className="flex justify-between gap-3"><div className="min-w-0"><h3 className="font-bold truncate">{doc.name}</h3><p className="text-sm muted mt-1">{doc.category} • {size(doc.file_size)}</p></div><div className="flex"><button className="icon-btn" onClick={()=>void downloadDocument(doc)} aria-label="Baixar"><Download size={16}/></button><button className="icon-btn danger" onClick={()=>void remove(doc)} aria-label="Excluir"><Trash2 size={16}/></button></div></div>{doc.description&&<p className="muted text-sm mt-3">{doc.description}</p>}<div className="flex flex-wrap gap-2 mt-3">{doc.tags.map(t=><span className="badge" key={t}>{t}</span>)}</div></div></div></article>)}{!filtered.length&&<div className="card p-12 text-center muted lg:col-span-2">Nenhum documento encontrado nesta campanha.</div>}</div>}
  {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="modal-card" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between items-start"><div><h2>Adicionar documento</h2><p>PDF, DOCX, PPTX, XLSX, TXT ou imagem, até 20 MB.</p></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X size={18}/></button></div><label>Arquivo *<div className="card p-6 text-center mt-2"><UploadCloud className="mx-auto mb-2"/><input name="file" type="file" required accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.csv,image/*"/></div></label><label>Descrição<textarea name="description" rows={3}/></label><div className="form-grid"><label>Categoria<select name="category" defaultValue="Estratégia">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Tags<input name="tags" placeholder="ex.: pesquisa, saúde, briefing"/></label></div><button disabled={saving} className="primary-btn justify-center">{saving&&<Loader2 size={17} className="animate-spin"/>} Enviar documento</button></form></div>}
 </div>
}
