"use client";
import {useEffect,useMemo,useState} from "react";
import {BriefcaseBusiness,Mail,MapPin,Phone,Plus,Search,ShieldCheck,Trash2,UserRound,X,Pencil} from "lucide-react";
import {Candidate,CandidateStatus,TeamMember,deleteCandidate,deleteTeamMember,listCandidates,listTeam,saveCandidate,saveTeamMember} from "@/lib/political-team-store";

const candidateEmpty={full_name:"",public_name:"",office:"",party:"",number:"",city:"",state:"SP",bio:"",slogan:"",instagram:"",phone:"",email:"",status:"pre_candidato" as CandidateStatus,photo_url:"",strengths:"",risks:""};
const memberEmpty={full_name:"",role:"",area:"Estratégia",email:"",phone:"",status:"ativo" as const,notes:""};
export default function PoliticalTeamManager(){
 const[tab,setTab]=useState<"candidates"|"team">("candidates"),[candidates,setCandidates]=useState<Candidate[]>([]),[team,setTeam]=useState<TeamMember[]>([]),[query,setQuery]=useState(""),[modal,setModal]=useState<null|"candidate"|"team">(null),[editId,setEditId]=useState<string|null>(null),[cf,setCf]=useState(candidateEmpty),[tf,setTf]=useState(memberEmpty),[error,setError]=useState("");
 async function refresh(){try{setError("");const[c,t]=await Promise.all([listCandidates(),listTeam()]);setCandidates(c);setTeam(t)}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar dados")}}
 useEffect(()=>{refresh();const f=()=>refresh();window.addEventListener("arcanum:campaign-changed",f);return()=>window.removeEventListener("arcanum:campaign-changed",f)},[]);
 const filteredCandidates=useMemo(()=>candidates.filter(c=>[c.full_name,c.public_name,c.office,c.party,c.city].join(" ").toLowerCase().includes(query.toLowerCase())),[candidates,query]);
 const filteredTeam=useMemo(()=>team.filter(m=>[m.full_name,m.role,m.area,m.email].join(" ").toLowerCase().includes(query.toLowerCase())),[team,query]);
 function newCandidate(){setEditId(null);setCf(candidateEmpty);setModal("candidate")} function editCandidate(c:Candidate){setEditId(c.id);setCf({...candidateEmpty,...c});setModal("candidate")}
 function newMember(){setEditId(null);setTf(memberEmpty);setModal("team")} function editMember(m:TeamMember){setEditId(m.id);setTf({full_name:m.full_name,role:m.role,area:m.area,email:m.email,phone:m.phone,status:m.status,notes:m.notes});setModal("team")}
 async function submitCandidate(e:React.FormEvent){e.preventDefault();await saveCandidate(cf,editId||undefined);setModal(null);refresh()}
 async function submitTeam(e:React.FormEvent){e.preventDefault();await saveTeamMember(tf,editId||undefined);setModal(null);refresh()}
 return <div className="space-y-6">
  <section className="page-hero flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><div className="eyebrow">GESTÃO POLÍTICA</div><h2 className="text-3xl font-black mt-2">Candidatos e equipe</h2><p className="muted mt-2">Cadastros vinculados automaticamente à campanha selecionada no topo.</p></div><button className="primary-btn" onClick={tab==="candidates"?newCandidate:newMember}><Plus size={18}/> {tab==="candidates"?"Novo candidato":"Novo integrante"}</button></section>
  <section className="grid md:grid-cols-3 gap-4"><div className="metric-card"><span className="metric-label">Candidatos</span><strong>{candidates.length}</strong><small>na campanha atual</small></div><div className="metric-card"><span className="metric-label">Equipe</span><strong>{team.length}</strong><small>integrantes cadastrados</small></div><div className="metric-card"><span className="metric-label">Áreas cobertas</span><strong>{new Set(team.map(x=>x.area).filter(Boolean)).size}</strong><small>núcleos operacionais</small></div></section>
  <div className="manager-tabs"><button className={tab==="candidates"?"active":""} onClick={()=>setTab("candidates")}><UserRound size={17}/> Candidatos</button><button className={tab==="team"?"active":""} onClick={()=>setTab("team")}><ShieldCheck size={17}/> Equipe</button></div>
  <div className="card p-4 flex items-center gap-3"><Search size={18} className="muted"/><input className="plain-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, cargo, partido ou área..."/></div>{error&&<div className="error-banner">{error}</div>}
  {tab==="candidates"?<div className="grid xl:grid-cols-2 gap-5">{filteredCandidates.map(c=><article className="profile-card" key={c.id}><div className="profile-avatar">{(c.public_name||c.full_name).split(" ").slice(0,2).map(x=>x[0]).join("")}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><span className={`status-pill ${c.status==="candidato"?"ativa":""}`}>{c.status.replace("_"," ")}</span><h3>{c.public_name||c.full_name}</h3><p>{c.full_name!==c.public_name?c.full_name:""}</p></div><div className="flex"><button className="icon-btn" onClick={()=>editCandidate(c)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={async()=>{if(confirm("Excluir candidato?")){await deleteCandidate(c.id);refresh()}}}><Trash2 size={16}/></button></div></div><div className="profile-meta"><span><BriefcaseBusiness size={15}/>{c.office||"Cargo não informado"}{c.party?` • ${c.party}`:""}</span><span><MapPin size={15}/>{c.city||"Cidade"}/{c.state}</span>{c.instagram&&<span>@{c.instagram.replace("@","")}</span>}</div>{c.slogan&&<blockquote>“{c.slogan}”</blockquote>}</div></article>)}{!filteredCandidates.length&&<Empty text="Nenhum candidato cadastrado nesta campanha."/>}</div>:
  <div className="grid xl:grid-cols-2 gap-5">{filteredTeam.map(m=><article className="profile-card" key={m.id}><div className="profile-avatar team">{m.full_name.split(" ").slice(0,2).map(x=>x[0]).join("")}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><span className={`status-pill ${m.status==="ativo"?"ativa":""}`}>{m.status}</span><h3>{m.full_name}</h3><p>{m.role} • {m.area}</p></div><div className="flex"><button className="icon-btn" onClick={()=>editMember(m)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={async()=>{if(confirm("Excluir integrante?")){await deleteTeamMember(m.id);refresh()}}}><Trash2 size={16}/></button></div></div><div className="profile-meta">{m.email&&<span><Mail size={15}/>{m.email}</span>}{m.phone&&<span><Phone size={15}/>{m.phone}</span>}</div>{m.notes&&<p className="mt-3 muted text-sm">{m.notes}</p>}</div></article>)}{!filteredTeam.length&&<Empty text="Nenhum integrante cadastrado nesta campanha."/>}</div>}
  {modal==="candidate"&&<Modal close={()=>setModal(null)} title={editId?"Editar candidato":"Novo candidato"}><form className="grid md:grid-cols-2 gap-4" onSubmit={submitCandidate}><Field label="Nome completo *"><input required value={cf.full_name} onChange={e=>setCf({...cf,full_name:e.target.value})}/></Field><Field label="Nome público"><input value={cf.public_name} onChange={e=>setCf({...cf,public_name:e.target.value})}/></Field><Field label="Cargo"><input value={cf.office} onChange={e=>setCf({...cf,office:e.target.value})}/></Field><Field label="Partido"><input value={cf.party} onChange={e=>setCf({...cf,party:e.target.value})}/></Field><Field label="Número"><input value={cf.number} onChange={e=>setCf({...cf,number:e.target.value})}/></Field><Field label="Status"><select value={cf.status} onChange={e=>setCf({...cf,status:e.target.value as CandidateStatus})}><option value="pre_candidato">Pré-candidato</option><option value="candidato">Candidato</option><option value="mandato">Mandato</option><option value="inativo">Inativo</option></select></Field><Field label="Cidade"><input value={cf.city} onChange={e=>setCf({...cf,city:e.target.value})}/></Field><Field label="UF"><input maxLength={2} value={cf.state} onChange={e=>setCf({...cf,state:e.target.value.toUpperCase()})}/></Field><Field label="Instagram"><input value={cf.instagram} onChange={e=>setCf({...cf,instagram:e.target.value})}/></Field><Field label="Telefone"><input value={cf.phone} onChange={e=>setCf({...cf,phone:e.target.value})}/></Field><Field label="E-mail"><input type="email" value={cf.email} onChange={e=>setCf({...cf,email:e.target.value})}/></Field><Field label="Slogan"><input value={cf.slogan} onChange={e=>setCf({...cf,slogan:e.target.value})}/></Field><Field wide label="Biografia"><textarea rows={3} value={cf.bio} onChange={e=>setCf({...cf,bio:e.target.value})}/></Field><Field label="Forças"><textarea rows={3} value={cf.strengths} onChange={e=>setCf({...cf,strengths:e.target.value})}/></Field><Field label="Riscos"><textarea rows={3} value={cf.risks} onChange={e=>setCf({...cf,risks:e.target.value})}/></Field><Actions/></form></Modal>}
  {modal==="team"&&<Modal close={()=>setModal(null)} title={editId?"Editar integrante":"Novo integrante"}><form className="grid md:grid-cols-2 gap-4" onSubmit={submitTeam}><Field label="Nome completo *"><input required value={tf.full_name} onChange={e=>setTf({...tf,full_name:e.target.value})}/></Field><Field label="Função *"><input required value={tf.role} onChange={e=>setTf({...tf,role:e.target.value})} placeholder="Coordenador, social media..."/></Field><Field label="Área"><select value={tf.area} onChange={e=>setTf({...tf,area:e.target.value})}><option>Estratégia</option><option>Comunicação</option><option>Jurídico</option><option>Mobilização</option><option>Financeiro</option><option>Agenda</option><option>Dados</option></select></Field><Field label="Status"><select value={tf.status} onChange={e=>setTf({...tf,status:e.target.value as typeof tf.status})}><option value="ativo">Ativo</option><option value="convidado">Convidado</option><option value="inativo">Inativo</option></select></Field><Field label="E-mail"><input type="email" value={tf.email} onChange={e=>setTf({...tf,email:e.target.value})}/></Field><Field label="Telefone"><input value={tf.phone} onChange={e=>setTf({...tf,phone:e.target.value})}/></Field><Field wide label="Observações"><textarea rows={4} value={tf.notes} onChange={e=>setTf({...tf,notes:e.target.value})}/></Field><Actions/></form></Modal>}
 </div>
}
function Empty({text}:{text:string}){return <div className="card p-10 text-center muted xl:col-span-2">{text}</div>}
function Modal({children,close,title}:{children:React.ReactNode;close:()=>void;title:string}){return <div className="modal-backdrop" onMouseDown={close}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between items-center"><h2>{title}</h2><button className="icon-btn" onClick={close}><X size={18}/></button></div>{children}</div></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?"md:col-span-2":""}`}><span>{label}</span>{children}</label>}
function Actions(){return <div className="md:col-span-2 flex justify-end"><button className="primary-btn" type="submit">Salvar</button></div>}
