"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarDays,Download,FileText,Loader2,Printer,RefreshCw} from "lucide-react";
import {Campaign,getActiveCampaignId,listCampaigns} from "@/lib/campaign-store";
import {CalendarEvent,listCalendarEvents} from "@/lib/calendar-store";
import {LibraryDocument,listDocuments} from "@/lib/library-store";

const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;

export default function ReportsManager(){
 const[campaign,setCampaign]=useState<Campaign|null>(null),[events,setEvents]=useState<CalendarEvent[]>([]),[docs,setDocs]=useState<LibraryDocument[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const[campaigns,calendar,documents]=await Promise.all([listCampaigns(),listCalendarEvents(),listDocuments()]);const active=getActiveCampaignId();setCampaign(campaigns.find(x=>x.id===active)||campaigns[0]||null);setEvents(calendar);setDocs(documents)}catch(e){setError(e instanceof Error?e.message:"Erro ao gerar relatório.")}finally{setLoading(false)}}
 useEffect(()=>{queueMicrotask(()=>void load());const h=()=>void load();window.addEventListener("arcanum:campaign-changed",h);return()=>window.removeEventListener("arcanum:campaign-changed",h)},[]);
 const stats=useMemo(()=>({total:events.length,done:events.filter(x=>x.status==="concluido").length,pending:events.filter(x=>!["concluido","cancelado"].includes(x.status)).length,docs:docs.length}),[events,docs]);
 const upcoming=useMemo(()=>events.filter(x=>new Date(x.starts_at)>=new Date()&&x.status!=="cancelado").slice(0,8),[events]);
 function exportCsv(){const rows=[["Campanha",campaign?.name||""],["Candidato",campaign?.candidate_name||""],[],["Evento","Tipo","Status","Início","Local","Responsável"],...events.map(x=>[x.title,x.event_type,x.status,x.starts_at,x.location,x.responsible]),[],["Documento","Categoria","Tamanho","Criado em"],...docs.map(x=>[x.name,x.category,x.file_size,x.created_at])];const csv=rows.map(r=>r.map(csvCell).join(";")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`relatorio-${(campaign?.name||"campanha").toLowerCase().replace(/[^a-z0-9]+/g,"-")}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(loading)return <div className="card p-14 grid place-items-center"><Loader2 className="animate-spin"/></div>;
 return <div className="space-y-6">
  <section className="page-hero flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><span className="eyebrow">INTELIGÊNCIA GERENCIAL</span><h1>Relatórios da campanha</h1><p>{campaign?`${campaign.name} • ${campaign.candidate_name}`:"Selecione ou cadastre uma campanha."}</p></div><div className="flex flex-wrap gap-2"><button className="secondary-btn" onClick={()=>void load()}><RefreshCw size={17}/> Atualizar</button><button className="secondary-btn" onClick={()=>window.print()}><Printer size={17}/> Imprimir</button><button className="primary-btn" onClick={exportCsv}><Download size={17}/> Exportar CSV</button></div></section>
  {error&&<div className="error-banner">{error}</div>}
  <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><div className="metric-card"><span className="metric-label">Agenda total</span><strong>{stats.total}</strong><small>eventos cadastrados</small></div><div className="metric-card"><span className="metric-label">Concluídos</span><strong>{stats.done}</strong><small>{stats.total?Math.round(stats.done/stats.total*100):0}% da agenda</small></div><div className="metric-card"><span className="metric-label">Pendentes</span><strong>{stats.pending}</strong><small>exigem acompanhamento</small></div><div className="metric-card"><span className="metric-label">Biblioteca</span><strong>{stats.docs}</strong><small>documentos da campanha</small></div></section>
  <section className="grid xl:grid-cols-2 gap-5"><div className="card p-5"><div className="flex items-center gap-3 mb-5"><CalendarDays size={20}/><div><h2>Próximos compromissos</h2><p className="muted text-sm">Agenda futura da campanha.</p></div></div><div className="space-y-3">{upcoming.map(x=><div key={x.id} className="border border-[var(--border)] rounded-xl p-4"><div className="flex justify-between gap-3"><strong>{x.title}</strong><span className="badge">{x.status}</span></div><p className="muted text-sm mt-2">{date(x.starts_at)}{x.location?` • ${x.location}`:""}</p></div>)}{!upcoming.length&&<p className="muted">Nenhum compromisso futuro cadastrado.</p>}</div></div><div className="card p-5"><div className="flex items-center gap-3 mb-5"><FileText size={20}/><div><h2>Documentos recentes</h2><p className="muted text-sm">Últimos itens adicionados à biblioteca.</p></div></div><div className="space-y-3">{docs.slice(0,8).map(x=><div key={x.id} className="border border-[var(--border)] rounded-xl p-4"><div className="flex justify-between gap-3"><strong className="truncate">{x.name}</strong><span className="badge">{x.category}</span></div><p className="muted text-sm mt-2">Adicionado em {date(x.created_at)}</p></div>)}{!docs.length&&<p className="muted">Nenhum documento cadastrado.</p>}</div></div></section>
 </div>
}
