"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {menu} from "@/data/content";
import {Menu,Sun,Moon,LogOut,PanelLeftClose,PanelLeftOpen,LayoutDashboard,Users,GitCompare,Target,Megaphone,Palette,Share2,Library,Newspaper,ClipboardList,CalendarDays,FileText,Settings,Bell,ChevronRight,Radar,Clapperboard,Bot,CheckCheck,ExternalLink} from "lucide-react";
import {useEffect,useMemo,useState} from "react";import {useTheme} from "next-themes";import CommandPalette from "./CommandPalette";import CampaignSelector from "./CampaignSelector";import {createClient} from "@/lib/supabase/client";
const icons=[LayoutDashboard,Target,Users,GitCompare,Target,Radar,Clapperboard,Megaphone,Palette,Share2,Library,Newspaper,ClipboardList,CalendarDays,FileText,Bot,Settings];
type AppNotification={id:string;title:string;message:string;createdAt:string;read:boolean;href?:string};
const NOTIFICATIONS_KEY="arcanum:notifications";
function readNotifications():AppNotification[]{try{return JSON.parse(localStorage.getItem(NOTIFICATIONS_KEY)||"[]")}catch{return[]}}
function when(value:string){const diff=Math.max(0,Date.now()-new Date(value).getTime()),minutes=Math.floor(diff/60000);if(minutes<1)return"agora";if(minutes<60)return`há ${minutes} min`;const hours=Math.floor(minutes/60);if(hours<24)return`há ${hours}h`;return`há ${Math.floor(hours/24)}d`}
export default function Shell({children,title}:{children:React.ReactNode,title:string}){
 const p=usePathname();const [open,setOpen]=useState(true);const [mobile,setMobile]=useState(false);const [notificationOpen,setNotificationOpen]=useState(false);const [notifications,setNotifications]=useState<AppNotification[]>([]);const {theme,setTheme}=useTheme();const supabase=createClient();async function logout(){if(supabase)await supabase.auth.signOut();await fetch("/auth/logout",{method:"POST"});window.location.href="/login";}
 useEffect(()=>{const load=()=>setNotifications(readNotifications());load();window.addEventListener("arcanum:notifications-changed",load);window.addEventListener("storage",load);return()=>{window.removeEventListener("arcanum:notifications-changed",load);window.removeEventListener("storage",load)}},[]);
 const unread=useMemo(()=>notifications.filter(n=>!n.read).length,[notifications]);
 function save(next:AppNotification[]){setNotifications(next);localStorage.setItem(NOTIFICATIONS_KEY,JSON.stringify(next));window.dispatchEvent(new Event("arcanum:notifications-changed"))}
 function markAll(){save(notifications.map(n=>({...n,read:true})))}
 function openNotification(item:AppNotification){save(notifications.map(n=>n.id===item.id?{...n,read:true}:n));setNotificationOpen(false)}
 return <div className="min-h-screen flex">
 <aside className={`${open?'w-72':'w-24'} hidden md:flex flex-col fixed inset-y-0 left-0 p-4 transition-all duration-300`}><div className="sidebar-shell h-full flex flex-col p-3"><div className="flex items-center justify-between p-3"><div className="flex items-center gap-3"><div className="logo-mark">A</div>{open&&<div><div className="font-black text-lg tracking-[.12em]">ARCANUM</div><div className="text-[10px] muted">STRATEGY OS</div></div>}</div><button aria-label="Recolher menu" className="icon-btn" onClick={()=>setOpen(!open)}>{open?<PanelLeftClose size={17}/>:<PanelLeftOpen size={17}/>}</button></div>
 {open&&<div className="px-3 mt-4 mb-2 text-[10px] font-bold muted tracking-[.16em]">NAVEGAÇÃO</div>}
 <nav className="flex-1 overflow-auto space-y-1">{menu.map(([href,label],i)=>{const Icon=icons[i];return <Link key={href} href={href} title={label} className={`nav-item ${p===href?'active':''}`}><Icon size={18}/>{open&&<><span className="flex-1">{label}</span>{p===href&&<ChevronRight size={15}/>}</>}</Link>})}</nav>
 <div className="sidebar-user"><div className="avatar">MK</div>{open&&<div className="min-w-0"><div className="text-sm font-semibold truncate">Marketing 2026</div><div className="text-xs muted">{supabase?"Supabase conectado":"Modo demonstração"}</div></div>}</div></div></aside>
 {mobile&&<div className="fixed inset-0 z-50 bg-black/45 md:hidden" onClick={()=>setMobile(false)}><div className="w-72 h-full bg-[var(--card)] p-4" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 mb-6"><div className="logo-mark">A</div><b>ARCANUM</b></div>{menu.map(([href,label],i)=>{const Icon=icons[i];return <Link key={href} href={href} onClick={()=>setMobile(false)} className="nav-item"><Icon size={18}/>{label}</Link>})}</div></div>}
 <main className={`${open?'md:ml-72':'md:ml-24'} flex-1 min-w-0 transition-all duration-300`}><header className="topbar"><div className="flex gap-3 items-center"><button className="md:hidden icon-btn" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><h1 className="text-xl font-bold tracking-tight">{title}</h1><p className="text-xs muted">Inteligência estratégica <span className="mx-1">•</span> Dados de demonstração</p></div></div><div className="flex gap-2 items-center"><CampaignSelector/><CommandPalette/><div className="relative"><button className="icon-btn relative" aria-label="Notificações" onClick={()=>setNotificationOpen(v=>!v)}><Bell size={18}/>{unread>0&&<span className="absolute -top-1 -right-1 min-w-5 h-5 px-1 rounded-full bg-red-600 text-white text-[10px] font-bold grid place-items-center">{unread>9?"9+":unread}</span>}</button>{notificationOpen&&<div className="absolute right-0 top-12 z-50 w-[min(92vw,420px)] card shadow-2xl overflow-hidden"><div className="p-4 border-b border-[var(--border)] flex items-center justify-between"><div><strong>Notificações</strong><p className="text-xs muted">Alertas do Radar Político</p></div><button className="text-xs flex items-center gap-1 muted" onClick={markAll}><CheckCheck size={15}/> Marcar como lidas</button></div><div className="max-h-[420px] overflow-auto">{notifications.map(item=><Link key={item.id} href={item.href||"/clipping"} onClick={()=>openNotification(item)} className={`block p-4 border-b border-[var(--border)] hover:bg-[var(--soft)] ${item.read?"opacity-70":""}`}><div className="flex gap-3"><div className={`mt-1 h-2.5 w-2.5 rounded-full shrink-0 ${item.read?"bg-slate-400":"bg-red-500"}`}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><strong className="text-sm">{item.title}</strong><ExternalLink size={14} className="shrink-0 muted"/></div><p className="text-xs mt-1 line-clamp-2">{item.message}</p><span className="text-[11px] muted mt-2 block">{when(item.createdAt)}</span></div></div></Link>)}{!notifications.length&&<div className="p-10 text-center muted"><Bell className="mx-auto mb-3"/><p className="text-sm">Nenhuma notificação.</p></div>}</div></div>}</div><button className="icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={logout} className="icon-btn" aria-label="Sair"><LogOut size={18}/></button></div></header><div className="p-4 md:p-8 max-w-[1680px] mx-auto">{children}</div></main></div>
}
