"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {menu} from "@/data/content";
import {Menu,Sun,Moon,LogOut,PanelLeftClose,PanelLeftOpen,LayoutDashboard,Users,GitCompare,Target,Megaphone,Palette,Share2,Library,Newspaper,ClipboardList,CalendarDays,FileText,Settings,Bell,ChevronRight,Radar,Clapperboard,Bot,CheckCheck,ExternalLink} from "lucide-react";
import {useEffect,useMemo,useState} from "react";import {useTheme} from "next-themes";import CommandPalette from "./CommandPalette";import CampaignSelector from "./CampaignSelector";import {createClient} from "@/lib/supabase/client";import {getCurrentAccess,Permission} from "./AccessManager";
const icons=[LayoutDashboard,Target,Users,GitCompare,Target,Radar,Clapperboard,Megaphone,Palette,Share2,Library,Newspaper,ClipboardList,CalendarDays,FileText,Bot,Settings];
type AppNotification={id:string;title:string;message:string;createdAt:string;read:boolean;href?:string};
const NOTIFICATIONS_KEY="arcanum:notifications";
function readNotifications():AppNotification[]{try{return JSON.parse(localStorage.getItem(NOTIFICATIONS_KEY)||"[]")}catch{return[]}}
function when(value:string){const diff=Math.max(0,Date.now()-new Date(value).getTime()),minutes=Math.floor(diff/60000);if(minutes<1)return"agora";if(minutes<60)return`há ${minutes} min`;const hours=Math.floor(minutes/60);if(hours<24)return`há ${hours}h`;return`há ${Math.floor(hours/24)}d`}
function requiredPermission(href:string):Permission|undefined{if(href==="/configuracoes")return"settings";if(href==="/clipping")return"radar";if(href==="/biblioteca")return"library";if(href==="/relatorios")return"reports";if(["/conteudo","/marketing","/branding","/redes-sociais"].includes(href))return"content"}
export default function Shell({children,title}:{children:React.ReactNode,title:string}){
 const p=usePathname();const [open,setOpen]=useState(true);const [mobile,setMobile]=useState(false);const [notificationOpen,setNotificationOpen]=useState(false);const [notifications,setNotifications]=useState<AppNotification[]>([]);const [email,setEmail]=useState<string|null>(null);const [permissionTick,setPermissionTick]=useState(0);const {theme,setTheme}=useTheme();const supabase=createClient();async function logout(){if(supabase)await supabase.auth.signOut();await fetch("/auth/logout",{method:"POST"});window.location.href="/login";}
 useEffect(()=>{const load=()=>setNotifications(readNotifications());load();window.addEventListener("arcanum:notifications-changed",load);window.addEventListener("storage",load);return()=>{window.removeEventListener("arcanum:notifications-changed",load);window.removeEventListener("storage",load)}},[]);
 useEffect(()=>{void supabase?.auth.getUser().then(({data})=>setEmail(data.user?.email||null));const h=()=>setPermissionTick(x=>x+1);window.addEventListener("arcanum:permissions-changed",h);return()=>window.removeEventListener("arcanum:permissions-changed",h)},[supabase]);
 const access=useMemo(()=>getCurrentAccess(email),[email,permissionTick]);
 const visibleMenu=useMemo(()=>menu.filter(([href])=>{const required=requiredPermission(href);if(!required)return true;if(access.admin||access.permissions.includes("all_modules"))return true;return access.permissions.includes(required)}),[access]);
 const unread=useMemo(()=>notifications.filter(n=>!n.read).length,[notifications]);
 function save(next:AppNotification[]){setNotifications(next);localStorage.setItem(NOTIFICATIONS_KEY,JSON.stringify(next));window.dispatchEvent(new Event("arcanum:notifications-changed"))}
 function markAll(){save(notifications.map(n=>({...n,read:true})))}
 function openNotification(item:AppNotification){save(notifications.map(n=>n.id===item.id?{...n,read:true}:n));setNotificationOpen(false)}
 function navItems(closeMobile=false){return visibleMenu.map(([href,label])=>{const i=menu.findIndex(x=>x[0]===href),Icon=icons[i];return <Link key={href} href={href} title={label} onClick={()=>closeMobile&&setMobile(false)} className={`nav-item ${p===href?'active':''}`}><span className="nav-icon"><Icon size={18}/></span>{open||closeMobile?<><span className="flex-1 truncate">{label}</span>{p===href&&<ChevronRight size={15}/>}</>:null}</Link>})}
 return <div className="min-h-screen flex">
 <aside className={`${open?'sidebar-open':'sidebar-closed'} app-sidebar hidden md:flex`}><div className="sidebar-shell h-full flex flex-col"><div className="sidebar-brand"><div className="flex items-center gap-3 min-w-0"><div className="logo-mark shrink-0">A</div>{open&&<div className="min-w-0"><div className="font-black text-lg tracking-[.12em] truncate">ARCANUM</div><div className="text-[10px] muted">STRATEGY OS</div></div>}</div><button aria-label="Recolher menu" className="icon-btn shrink-0" onClick={()=>setOpen(!open)}>{open?<PanelLeftClose size={17}/>:<PanelLeftOpen size={17}/>}</button></div>
 {open&&<div className="sidebar-label">NAVEGAÇÃO</div>}
 <nav className="sidebar-nav">{navItems()}</nav>
 <div className="sidebar-user"><div className="avatar">{access.admin?"JA":"MK"}</div>{open&&<div className="min-w-0"><div className="text-sm font-semibold truncate">{access.admin?"Administrador":"Marketing 2026"}</div><div className="text-xs muted truncate">{email||"Supabase conectado"}</div></div>}</div></div></aside>
 {mobile&&<div className="fixed inset-0 z-50 bg-black/55 backdrop-blur-sm md:hidden" onClick={()=>setMobile(false)}><div className="mobile-sidebar" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 mb-6"><div className="logo-mark">A</div><b>ARCANUM</b></div><nav className="space-y-1">{navItems(true)}</nav></div></div>}
 <main className={`${open?'md:ml-[292px]':'md:ml-[92px]'} flex-1 min-w-0 transition-all duration-300`}><header className="topbar"><div className="flex gap-3 items-center min-w-0"><button className="md:hidden icon-btn" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="min-w-0"><h1 className="text-xl font-bold tracking-tight truncate">{title}</h1><p className="text-xs muted truncate">Inteligência estratégica <span className="mx-1">•</span> Ambiente operacional</p></div></div><div className="flex gap-2 items-center"><CampaignSelector/><CommandPalette/><div className="relative"><button className="icon-btn relative" aria-label="Notificações" onClick={()=>setNotificationOpen(v=>!v)}><Bell size={18}/>{unread>0&&<span className="notification-count">{unread>9?"9+":unread}</span>}</button>{notificationOpen&&<div className="notification-popover"><div className="p-4 border-b border-[var(--border)] flex items-center justify-between"><div><strong>Notificações</strong><p className="text-xs muted">Alertas do Radar Político</p></div><button className="text-xs flex items-center gap-1 muted" onClick={markAll}><CheckCheck size={15}/> Marcar como lidas</button></div><div className="max-h-[420px] overflow-auto">{notifications.map(item=><Link key={item.id} href={item.href||"/clipping"} onClick={()=>openNotification(item)} className={`notification-item ${item.read?"opacity-65":""}`}><span className={`notification-dot ${item.read?"read":""}`}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><strong className="text-sm">{item.title}</strong><ExternalLink size={14} className="shrink-0 muted"/></div><p className="text-xs mt-1 line-clamp-2">{item.message}</p><span className="text-[11px] muted mt-2 block">{when(item.createdAt)}</span></div></Link>)}{!notifications.length&&<div className="p-10 text-center muted"><Bell className="mx-auto mb-3"/><p className="text-sm">Nenhuma notificação.</p></div>}</div></div>}</div><button className="icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={logout} className="icon-btn" aria-label="Sair"><LogOut size={18}/></button></div></header><div className="p-4 md:p-8 max-w-[1680px] mx-auto">{children}</div></main></div>
}
